variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  # DATEBASE_URL: can be added

cache:
  paths:
    - .cache/pip

deploy:
  stage: deploy
  tags:
    - ci-apps-dev-srv
  script: 
    - echo "Starting deploy!"
    - pip install -r requirements.txt
    - cd /home/developer/ac-searcher/
    - git reset --hard HEAD
    - git pull origin master
    - cp /home/developer/config.py /home/developer/ac-searcher/src/ac_searcher/config.py
    - cp /home/developer/proxy.py /home/developer/ac-searcher/src/ac_searcher/proxy.py
    - sudo systemctl restart ac-searcher.service
  environment: production